# Copyright 2025 The RLinf Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Derive and authenticate a RoboTwin pi0.5 Draft from a pi0 warm start.

The published Realtime-VLA FLASH heads are seven-dimensional LIBERO/pi0
artifacts.  This module deliberately provides no conversion that can bless
those bytes for direct pi0.5 inference.  A published head may enter only the
warm-start function below.  That function copies the state token, H=50 query
tokens, and Gemma decoder block, while a new 32-dimensional output layer is
initialized from scratch.

Production authorization is a separate, content-addressed chain:

* training exports an immutable *candidate* safetensors file and manifest;
* an evaluation report binds that exact manifest;
* an Ed25519 approval signs the candidate, target, weights, and evaluation;
* the production loader re-verifies every hash, tensor key/shape/dtype, target
  semantic field, and signature before returning an inference-only adapter.

No metric or experiment result is generated by this module.  All metrics in
an artifact are supplied by the completed training/evaluation process.
"""

from __future__ import annotations

import base64
import hashlib
import json
import math
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from types import MappingProxyType
from typing import Any, Literal

import torch
from torch import nn
from torch.nn import functional as F

from ..draft_assets import (
    PUBLISHED_CODE_REPOSITORY,
    PUBLISHED_CODE_REVISION,
    PUBLISHED_MODEL_REPOSITORY,
    PUBLISHED_MODEL_REVISION,
)
from ..errors import ConfigurationError, OptionalDependencyError, ShapeMismatchError
from .draft_head import DraftChunkHead

PI05_DRAFT_ARTIFACT_KIND = "fibocom_pi05_robotwin_draft_candidate"
PI05_DRAFT_ARCHITECTURE = "gemma_query_decoder_h50_state32_model_action32_v1"
PI05_DRAFT_PARAMETER_COUNT = 110_340_128
PI05_ACTION_HORIZON = 50
PI05_MODEL_ACTION_DIM = 32
PI05_ENV_ACTION_DIM = 14
PI05_MODEL_STATE_DIM = 32
PI05_RAW_STATE_DIM = 14
PI05_PREFIX_EMBEDDING_DIM = 2048
PI05_MAX_TOKEN_LENGTH = 200
PI05_PARENT_REPOSITORY_ID = "RLinf/RLinf-Pi05-RoboTwin-SFT-adjust_bottle"
PI05_PARENT_REVISION = "fa8df6ed103db0f5549c122f3a17c00ba6426c98"

_PUBLISHED_PARENT_SHA256S = frozenset(
    {
        "371d809745d688e03b2a09ccb89b509906530c7db48117236caf13e676333f17",
        "33724426753c3b3a4ad5b0c3510bf5ac9255ee6338724bb5c58c7ea8b60429a1",
        "ef4fec6fa4d7d013eb5d54123501159e066d80fa5d23f96690d5bd8aaf397c0a",
        "88ef0bbf2ff89d51beaa742fc8a9cb0b1cbfc027282182e1f366f93895fed622",
    }
)

_RAW_CAMERA_KEYS = ("cam_high", "cam_left_wrist", "cam_right_wrist")
_MODEL_CAMERA_KEYS = ("base_0_rgb", "left_wrist_0_rgb", "right_wrist_0_rgb")
_ACTION_SEMANTICS = (
    "left_joint_1",
    "left_joint_2",
    "left_joint_3",
    "left_joint_4",
    "left_joint_5",
    "left_joint_6",
    "left_gripper",
    "right_joint_1",
    "right_joint_2",
    "right_joint_3",
    "right_joint_4",
    "right_joint_5",
    "right_joint_6",
    "right_gripper",
)
_DELTA_ACTION_MASK = (
    True,
    True,
    True,
    True,
    True,
    True,
    False,
    True,
    True,
    True,
    True,
    True,
    True,
    False,
)
_ENV_ACTION_INDICES = tuple(range(PI05_ENV_ACTION_DIM))
_ACTIVE_JOINT_INDICES = (0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12)
_GRIPPER_INDICES = (6, 13)

_TARGET_STATE_SHAPES: Mapping[str, tuple[int, ...]] = MappingProxyType(
    {
        "_state_token.weight": (2048, 32),
        "_state_token.bias": (2048,),
        "_action_queries.weight": (50, 2048),
        "_gemma_block.self_attn.q_proj.weight": (2048, 2048),
        "_gemma_block.self_attn.k_proj.weight": (256, 2048),
        "_gemma_block.self_attn.v_proj.weight": (256, 2048),
        "_gemma_block.self_attn.o_proj.weight": (2048, 2048),
        "_gemma_block.mlp.gate_proj.weight": (16384, 2048),
        "_gemma_block.mlp.up_proj.weight": (16384, 2048),
        "_gemma_block.mlp.down_proj.weight": (2048, 16384),
        "_gemma_block.input_layernorm.weight": (2048,),
        "_gemma_block.post_attention_layernorm.weight": (2048,),
        "_action_head.weight": (32, 2048),
        "_action_head.bias": (32,),
    }
)
_SOURCE_ACTION_SHAPES = {
    "_action_head.weight": (7, 2048),
    "_action_head.bias": (7,),
}
_REINITIALIZED_KEYS = tuple(sorted(_SOURCE_ACTION_SHAPES))
_COPIED_KEYS = tuple(sorted(set(_TARGET_STATE_SHAPES) - set(_REINITIALIZED_KEYS)))
_PRODUCTION_AUTHORIZATION_TOKEN = object()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _canonical_json_bytes(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as error:
        raise ConfigurationError(f"value is not canonical JSON: {error}") from error


def _canonical_sha256(value: Any) -> str:
    return hashlib.sha256(_canonical_json_bytes(value)).hexdigest()


def _require_string(value: Any, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigurationError(f"{name} must be a non-empty string")
    return value.strip()


def _require_sha256(value: Any, name: str) -> str:
    digest = _require_string(value, name).lower()
    if len(digest) != 64 or any(char not in "0123456789abcdef" for char in digest):
        raise ConfigurationError(f"{name} must be a SHA-256 digest")
    return digest


def _require_revision(value: Any, name: str) -> str:
    revision = _require_string(value, name).lower()
    if len(revision) != 40 or any(char not in "0123456789abcdef" for char in revision):
        raise ConfigurationError(f"{name} must be a 40-character commit revision")
    return revision


def _require_exact_keys(
    data: Mapping[str, Any], expected: set[str], *, name: str
) -> None:
    observed = set(data)
    if observed != expected:
        missing = sorted(expected - observed)
        unexpected = sorted(observed - expected)
        raise ConfigurationError(
            f"{name} keys mismatch: missing={missing}, unexpected={unexpected}"
        )


def _json_object_copy(value: Mapping[str, Any], name: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ConfigurationError(f"{name} must be a JSON object")
    decoded = json.loads(_canonical_json_bytes(dict(value)).decode("utf-8"))
    if not isinstance(decoded, dict):
        raise ConfigurationError(f"{name} must serialize to a JSON object")
    return MappingProxyType(decoded)


def _dtype_name(dtype: torch.dtype) -> str:
    names = {
        torch.float32: "float32",
        torch.bfloat16: "bfloat16",
    }
    try:
        return names[dtype]
    except KeyError as error:
        raise ConfigurationError(
            f"unsupported Draft parameter dtype: {dtype}"
        ) from error


def _torch_dtype(name: str) -> torch.dtype:
    names = {"float32": torch.float32, "bfloat16": torch.bfloat16}
    try:
        return names[name]
    except KeyError as error:
        raise ConfigurationError(
            "draft_parameter_dtype must be 'float32' or 'bfloat16'"
        ) from error


@dataclass(frozen=True, kw_only=True)
class Pi05DraftTargetContract:
    """Exact main-checkpoint and RoboTwin transform contract for a Draft."""

    parent_repository_id: str
    parent_revision: str
    parent_asset_manifest_sha256: str
    norm_stats_sha256: str
    transform_id: str
    transform_source_sha256: tuple[str, ...]
    draft_parameter_dtype: Literal["float32", "bfloat16"] = "bfloat16"
    model_family: str = "pi0.5"
    config_name: str = "pi05_aloha_robotwin"
    asset_id: str = "physical-intelligence/robotwin"
    norm_stats_path: str = "physical-intelligence/robotwin/norm_stats.json"
    normalization: str = "quantile_q01_q99"
    action_horizon: int = PI05_ACTION_HORIZON
    model_action_dim: int = PI05_MODEL_ACTION_DIM
    environment_action_dim: int = PI05_ENV_ACTION_DIM
    raw_state_dim: int = PI05_RAW_STATE_DIM
    model_state_dim: int = PI05_MODEL_STATE_DIM
    prefix_embedding_dim: int = PI05_PREFIX_EMBEDDING_DIM
    max_token_length: int = PI05_MAX_TOKEN_LENGTH
    raw_camera_keys: tuple[str, ...] = _RAW_CAMERA_KEYS
    model_camera_keys: tuple[str, ...] = _MODEL_CAMERA_KEYS
    state_semantics: tuple[str, ...] = _ACTION_SEMANTICS
    environment_action_semantics: tuple[str, ...] = _ACTION_SEMANTICS
    environment_action_indices: tuple[int, ...] = _ENV_ACTION_INDICES
    delta_action_mask: tuple[bool, ...] = _DELTA_ACTION_MASK
    gripper_indices: tuple[int, ...] = _GRIPPER_INDICES
    adapt_to_pi: bool = True
    extra_delta_transform: bool = True

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "parent_repository_id",
            _require_string(self.parent_repository_id, "parent_repository_id"),
        )
        object.__setattr__(
            self,
            "parent_revision",
            _require_revision(self.parent_revision, "parent_revision"),
        )
        object.__setattr__(
            self,
            "parent_asset_manifest_sha256",
            _require_sha256(
                self.parent_asset_manifest_sha256,
                "parent_asset_manifest_sha256",
            ),
        )
        object.__setattr__(
            self,
            "norm_stats_sha256",
            _require_sha256(self.norm_stats_sha256, "norm_stats_sha256"),
        )
        object.__setattr__(
            self, "transform_id", _require_string(self.transform_id, "transform_id")
        )
        source_hashes = tuple(
            _require_sha256(value, f"transform_source_sha256[{index}]")
            for index, value in enumerate(self.transform_source_sha256)
        )
        if not source_hashes:
            raise ConfigurationError("transform_source_sha256 must not be empty")
        object.__setattr__(self, "transform_source_sha256", source_hashes)
        _torch_dtype(self.draft_parameter_dtype)

        fixed_values = {
            "parent_repository_id": PI05_PARENT_REPOSITORY_ID,
            "parent_revision": PI05_PARENT_REVISION,
            "model_family": "pi0.5",
            "config_name": "pi05_aloha_robotwin",
            "asset_id": "physical-intelligence/robotwin",
            "norm_stats_path": "physical-intelligence/robotwin/norm_stats.json",
            "normalization": "quantile_q01_q99",
            "action_horizon": PI05_ACTION_HORIZON,
            "model_action_dim": PI05_MODEL_ACTION_DIM,
            "environment_action_dim": PI05_ENV_ACTION_DIM,
            "raw_state_dim": PI05_RAW_STATE_DIM,
            "model_state_dim": PI05_MODEL_STATE_DIM,
            "prefix_embedding_dim": PI05_PREFIX_EMBEDDING_DIM,
            "max_token_length": PI05_MAX_TOKEN_LENGTH,
            "raw_camera_keys": _RAW_CAMERA_KEYS,
            "model_camera_keys": _MODEL_CAMERA_KEYS,
            "state_semantics": _ACTION_SEMANTICS,
            "environment_action_semantics": _ACTION_SEMANTICS,
            "environment_action_indices": _ENV_ACTION_INDICES,
            "delta_action_mask": _DELTA_ACTION_MASK,
            "gripper_indices": _GRIPPER_INDICES,
            "adapt_to_pi": True,
            "extra_delta_transform": True,
        }
        mismatches = [
            name
            for name, expected in fixed_values.items()
            if getattr(self, name) != expected
        ]
        if mismatches:
            raise ConfigurationError(
                "pi0.5 RoboTwin target contract mismatch: " + ", ".join(mismatches)
            )

    def to_dict(self) -> dict[str, Any]:
        """Return a canonical-JSON-compatible target contract."""

        return {
            "parent_repository_id": self.parent_repository_id,
            "parent_revision": self.parent_revision,
            "parent_asset_manifest_sha256": self.parent_asset_manifest_sha256,
            "norm_stats_sha256": self.norm_stats_sha256,
            "transform_id": self.transform_id,
            "transform_source_sha256": list(self.transform_source_sha256),
            "draft_parameter_dtype": self.draft_parameter_dtype,
            "model_family": self.model_family,
            "config_name": self.config_name,
            "asset_id": self.asset_id,
            "norm_stats_path": self.norm_stats_path,
            "normalization": self.normalization,
            "action_horizon": self.action_horizon,
            "model_action_dim": self.model_action_dim,
            "environment_action_dim": self.environment_action_dim,
            "raw_state_dim": self.raw_state_dim,
            "model_state_dim": self.model_state_dim,
            "prefix_embedding_dim": self.prefix_embedding_dim,
            "max_token_length": self.max_token_length,
            "raw_camera_keys": list(self.raw_camera_keys),
            "model_camera_keys": list(self.model_camera_keys),
            "state_semantics": list(self.state_semantics),
            "environment_action_semantics": list(self.environment_action_semantics),
            "environment_action_indices": list(self.environment_action_indices),
            "delta_action_mask": list(self.delta_action_mask),
            "gripper_indices": list(self.gripper_indices),
            "adapt_to_pi": self.adapt_to_pi,
            "extra_delta_transform": self.extra_delta_transform,
        }

    @property
    def sha256(self) -> str:
        """Return the canonical target-contract digest."""

        return _canonical_sha256(self.to_dict())

    def require_matches_verified_openpi(self, verified_target: Any) -> None:
        """Bind this derived Draft to one actually verified and loaded main model."""

        from .openpi_speculative import VerifiedOpenPITarget

        if not isinstance(verified_target, VerifiedOpenPITarget):
            raise TypeError("verified_target must be a VerifiedOpenPITarget")
        verified_target.validate_runtime_model()
        assets = verified_target.assets
        main = verified_target.contract
        runtime = assets.manifest.runtime
        observed = {
            "parent_repository_id": assets.manifest.repository_id,
            "parent_revision": assets.manifest.revision,
            "parent_asset_manifest_sha256": _sha256_file(assets.manifest_path),
            "norm_stats_sha256": _sha256_file(assets.norm_stats_path),
            "transform_id": main.transform_id,
            "transform_source_sha256": tuple(
                source.sha256_lf for source in runtime.source_fingerprints
            ),
            "model_family": main.policy_family,
            "config_name": main.config_name,
            "asset_id": main.asset_id,
            "normalization": main.normalization,
            "action_horizon": main.action_horizon,
            "model_action_dim": main.model_action_dim,
            "environment_action_dim": len(main.env_action_indices),
            "model_state_dim": main.state_dim,
            "max_token_length": main.max_token_length,
            "raw_camera_keys": main.camera_keys,
            "model_camera_keys": main.model_camera_keys,
            "environment_action_semantics": main.environment_action_semantics,
            "environment_action_indices": main.env_action_indices,
            "delta_action_mask": main.delta_action_mask,
        }
        mismatches = [
            name for name, actual in observed.items() if getattr(self, name) != actual
        ]
        if self.raw_state_dim != runtime.state_dim:
            mismatches.append("raw_state_dim")
        if self.state_semantics != runtime.state_semantics:
            mismatches.append("state_semantics")
        if self.norm_stats_path != runtime.norm_stats_path.as_posix():
            mismatches.append("norm_stats_path")
        if mismatches:
            raise ConfigurationError(
                "signed pi0.5 Draft does not target the loaded OpenPI policy: "
                + ", ".join(dict.fromkeys(mismatches))
            )

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "Pi05DraftTargetContract":
        """Parse a target contract without accepting missing or extra fields."""

        if not isinstance(value, Mapping):
            raise ConfigurationError("target_contract must be an object")
        expected = set(cls.__dataclass_fields__)
        _require_exact_keys(value, expected, name="target_contract")
        tuple_fields = {
            "transform_source_sha256",
            "raw_camera_keys",
            "model_camera_keys",
            "state_semantics",
            "environment_action_semantics",
            "environment_action_indices",
            "delta_action_mask",
            "gripper_indices",
        }
        parsed = {
            key: tuple(item) if key in tuple_fields else item
            for key, item in value.items()
        }
        return cls(**parsed)

    @classmethod
    def from_verified_openpi(
        cls,
        verified_target: Any,
        *,
        draft_parameter_dtype: Literal["float32", "bfloat16"] = "bfloat16",
    ) -> "Pi05DraftTargetContract":
        """Derive the only admissible Draft target from a verified main load."""

        from .openpi_speculative import VerifiedOpenPITarget

        if not isinstance(verified_target, VerifiedOpenPITarget):
            raise TypeError("verified_target must be a VerifiedOpenPITarget")
        verified_target.validate_runtime_model()
        assets = verified_target.assets
        runtime = assets.manifest.runtime
        contract = cls(
            parent_repository_id=assets.manifest.repository_id,
            parent_revision=assets.manifest.revision,
            parent_asset_manifest_sha256=_sha256_file(assets.manifest_path),
            norm_stats_sha256=_sha256_file(assets.norm_stats_path),
            transform_id=verified_target.contract.transform_id,
            transform_source_sha256=tuple(
                source.sha256_lf for source in runtime.source_fingerprints
            ),
            draft_parameter_dtype=draft_parameter_dtype,
        )
        contract.require_matches_verified_openpi(verified_target)
        return contract


@dataclass(frozen=True)
class WarmStartLineage:
    """Content identity and the only allowed transfer map from public pi0."""

    checkpoint_filename: str
    checkpoint_size: int
    checkpoint_sha256: str
    initialization_seed: int
    copied_keys: tuple[str, ...] = _COPIED_KEYS
    reinitialized_keys: tuple[str, ...] = _REINITIALIZED_KEYS
    parent_model_repository: str = PUBLISHED_MODEL_REPOSITORY
    parent_model_revision: str = PUBLISHED_MODEL_REVISION
    parent_code_repository: str = PUBLISHED_CODE_REPOSITORY
    parent_code_revision: str = PUBLISHED_CODE_REVISION
    parent_model_family: str = "pi0"
    parent_config_name: str = "pi0_libero"
    use_policy: str = "warm_start_initialization_only"

    def __post_init__(self) -> None:
        filename = _require_string(self.checkpoint_filename, "checkpoint_filename")
        if Path(filename).name != filename:
            raise ConfigurationError("warm-start checkpoint must be a single filename")
        object.__setattr__(self, "checkpoint_filename", filename)
        if self.checkpoint_size <= 0:
            raise ConfigurationError("warm-start checkpoint_size must be positive")
        object.__setattr__(
            self,
            "checkpoint_sha256",
            _require_sha256(self.checkpoint_sha256, "warm-start checkpoint_sha256"),
        )
        if self.checkpoint_sha256 not in _PUBLISHED_PARENT_SHA256S:
            raise ConfigurationError(
                "warm-start lineage is not one of the four published SHA-256 assets"
            )
        if self.initialization_seed < 0:
            raise ConfigurationError("initialization_seed must be non-negative")
        fixed = {
            "copied_keys": _COPIED_KEYS,
            "reinitialized_keys": _REINITIALIZED_KEYS,
            "parent_model_repository": PUBLISHED_MODEL_REPOSITORY,
            "parent_model_revision": PUBLISHED_MODEL_REVISION,
            "parent_code_repository": PUBLISHED_CODE_REPOSITORY,
            "parent_code_revision": PUBLISHED_CODE_REVISION,
            "parent_model_family": "pi0",
            "parent_config_name": "pi0_libero",
            "use_policy": "warm_start_initialization_only",
        }
        mismatches = [
            name for name, expected in fixed.items() if getattr(self, name) != expected
        ]
        if mismatches:
            raise ConfigurationError(
                "warm-start lineage may not bless a different source: "
                + ", ".join(mismatches)
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "checkpoint_filename": self.checkpoint_filename,
            "checkpoint_size": self.checkpoint_size,
            "checkpoint_sha256": self.checkpoint_sha256,
            "initialization_seed": self.initialization_seed,
            "copied_keys": list(self.copied_keys),
            "reinitialized_keys": list(self.reinitialized_keys),
            "parent_model_repository": self.parent_model_repository,
            "parent_model_revision": self.parent_model_revision,
            "parent_code_repository": self.parent_code_repository,
            "parent_code_revision": self.parent_code_revision,
            "parent_model_family": self.parent_model_family,
            "parent_config_name": self.parent_config_name,
            "use_policy": self.use_policy,
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "WarmStartLineage":
        if not isinstance(value, Mapping):
            raise ConfigurationError("warm_start must be an object")
        expected = set(cls.__dataclass_fields__)
        _require_exact_keys(value, expected, name="warm_start")
        parsed = dict(value)
        parsed["copied_keys"] = tuple(parsed["copied_keys"])
        parsed["reinitialized_keys"] = tuple(parsed["reinitialized_keys"])
        return cls(**parsed)


@dataclass(frozen=True, kw_only=True)
class Pi05DraftTrainingRecord:
    """Caller-supplied, non-fabricated record of a completed training run."""

    dataset_manifest_sha256: str
    training_code_repository: str
    training_code_revision: str
    hparams: Mapping[str, Any]
    seed: int
    optimizer_steps: int
    metrics: Mapping[str, float]

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "dataset_manifest_sha256",
            _require_sha256(self.dataset_manifest_sha256, "dataset_manifest_sha256"),
        )
        object.__setattr__(
            self,
            "training_code_repository",
            _require_string(self.training_code_repository, "training_code_repository"),
        )
        object.__setattr__(
            self,
            "training_code_revision",
            _require_revision(self.training_code_revision, "training_code_revision"),
        )
        if (
            isinstance(self.seed, bool)
            or not isinstance(self.seed, int)
            or self.seed < 0
        ):
            raise ConfigurationError("training seed must be a non-negative integer")
        if (
            isinstance(self.optimizer_steps, bool)
            or not isinstance(self.optimizer_steps, int)
            or self.optimizer_steps <= 0
        ):
            raise ConfigurationError("optimizer_steps must be a positive integer")
        object.__setattr__(self, "hparams", _json_object_copy(self.hparams, "hparams"))
        if not isinstance(self.metrics, Mapping) or not self.metrics:
            raise ConfigurationError("training metrics must be a non-empty object")
        metrics: dict[str, float] = {}
        for name, value in self.metrics.items():
            metric_name = _require_string(name, "training metric name")
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ConfigurationError(
                    f"training metric {metric_name!r} must be numeric"
                )
            number = float(value)
            if not math.isfinite(number):
                raise ConfigurationError(
                    f"training metric {metric_name!r} is not finite"
                )
            metrics[metric_name] = number
        object.__setattr__(self, "metrics", MappingProxyType(metrics))

    def to_dict(self) -> dict[str, Any]:
        return {
            "dataset_manifest_sha256": self.dataset_manifest_sha256,
            "training_code_repository": self.training_code_repository,
            "training_code_revision": self.training_code_revision,
            "hparams": dict(self.hparams),
            "seed": self.seed,
            "optimizer_steps": self.optimizer_steps,
            "metrics": dict(self.metrics),
        }


@dataclass(frozen=True)
class Pi05DraftTransferReport:
    """Auditable result of the initialization-only transfer."""

    copied_keys: tuple[str, ...]
    reinitialized_keys: tuple[str, ...]
    copied_parameter_count: int
    target_parameter_count: int
    warm_start_sha256: str


class Pi05DraftChunkHead(DraftChunkHead):
    """H=50, state-32, prefix-2048, action-32 pi0.5 Draft candidate."""

    def __init__(
        self,
        *,
        target_contract: Pi05DraftTargetContract,
        warm_start_lineage: WarmStartLineage,
        initialization_seed: int,
        device: str | torch.device | None = None,
    ) -> None:
        self.target_contract = target_contract
        self.warm_start_lineage = warm_start_lineage
        self.initialization_seed = int(initialization_seed)
        target_device = torch.device(device) if device is not None else None
        dtype = _torch_dtype(target_contract.draft_parameter_dtype)
        if target_device is None:
            super().__init__(
                img_dim=PI05_PREFIX_EMBEDDING_DIM,
                chunk_m=PI05_ACTION_HORIZON,
                hidden_dim=16384,
                out_dim=PI05_MODEL_ACTION_DIM,
                num_heads=8,
                num_kv_heads=1,
                head_dim=256,
                dtype=dtype,
                attn_implementation="sdpa",
            )
        else:
            with torch.device(target_device):
                super().__init__(
                    img_dim=PI05_PREFIX_EMBEDDING_DIM,
                    chunk_m=PI05_ACTION_HORIZON,
                    hidden_dim=16384,
                    out_dim=PI05_MODEL_ACTION_DIM,
                    num_heads=8,
                    num_kv_heads=1,
                    head_dim=256,
                    dtype=dtype,
                    attn_implementation="sdpa",
                )
        self.to(device=target_device, dtype=dtype)
        self._optimizer_steps = 0
        self._source_checkpoint_path: Path | None = None
        self._production_authorized_pi05 = False
        self._production_artifact_manifest_sha256: str | None = None
        self._production_weights_sha256: str | None = None

    @property
    def base_model_family(self) -> str:
        return "pi0.5"

    @property
    def pi05_compatible(self) -> bool:
        return True

    @property
    def training_step_count(self) -> int:
        return int(self._optimizer_steps)

    @property
    def production_compatible(self) -> bool:
        return bool(self._production_authorized_pi05)

    @property
    def initialization_only(self) -> bool:
        return not self.production_compatible

    def record_completed_optimizer_step(self, loss: torch.Tensor) -> None:
        """Record one caller-executed optimizer step from a differentiable loss.

        This method does not perform or claim training.  The training loop must
        call it only after ``optimizer.step()`` for the supplied loss.
        """

        if not self.training:
            raise ConfigurationError(
                "optimizer steps can only be recorded in train mode"
            )
        if not isinstance(loss, torch.Tensor) or loss.ndim != 0:
            raise ConfigurationError("recorded training loss must be a scalar tensor")
        if not loss.requires_grad or loss.grad_fn is None:
            raise ConfigurationError("recorded training loss must be differentiable")
        if not bool(torch.isfinite(loss.detach()).item()):
            raise ConfigurationError("recorded training loss is not finite")
        self._optimizer_steps += 1

    def _authorize_production(
        self,
        token: object,
        *,
        artifact_manifest_sha256: str,
        weights_sha256: str,
    ) -> None:
        if token is not _PRODUCTION_AUTHORIZATION_TOKEN:
            raise ConfigurationError("invalid production authorization token")
        self._production_authorized_pi05 = True
        self._production_artifact_manifest_sha256 = _require_sha256(
            artifact_manifest_sha256, "artifact_manifest_sha256"
        )
        self._production_weights_sha256 = _require_sha256(
            weights_sha256, "weights_sha256"
        )
        self.eval()
        self.requires_grad_(False)

    def production_predict_adapter(self) -> "Pi05DraftProductionAdapter":
        if not self.production_compatible:
            raise ConfigurationError(
                "untrained, unsigned, or candidate pi0.5 Draft cannot enter production"
            )
        return Pi05DraftProductionAdapter(self)

    def forward(
        self,
        *,
        prefix_embs: torch.Tensor,
        prefix_pad_masks: torch.Tensor,
        prefix_att_masks: torch.Tensor,
        robot_state: torch.Tensor,
        last_actions: torch.Tensor,
    ) -> torch.Tensor:
        if prefix_embs.ndim != 3 or int(prefix_embs.shape[-1]) != 2048:
            raise ShapeMismatchError("prefix_embs must be [B,S,2048]")
        batch, sequence = int(prefix_embs.shape[0]), int(prefix_embs.shape[1])
        if tuple(prefix_pad_masks.shape) != (batch, sequence):
            raise ShapeMismatchError("prefix_pad_masks must be [B,S]")
        if tuple(prefix_att_masks.shape) != (batch, sequence):
            raise ShapeMismatchError("prefix_att_masks must be [B,S]")
        if tuple(robot_state.shape) != (batch, PI05_MODEL_STATE_DIM):
            raise ShapeMismatchError("robot_state must be [B,32] model-space state")
        if (
            last_actions.ndim != 3
            or int(last_actions.shape[0]) != batch
            or int(last_actions.shape[1]) <= 0
            or int(last_actions.shape[2]) != PI05_MODEL_ACTION_DIM
        ):
            raise ShapeMismatchError("last_actions must be [B,L,32] with L > 0")
        output = super().forward(
            prefix_embs=prefix_embs,
            prefix_pad_masks=prefix_pad_masks,
            prefix_att_masks=prefix_att_masks,
            robot_state=robot_state,
            last_actions=last_actions,
        )
        if tuple(output.shape) != (batch, PI05_ACTION_HORIZON, PI05_MODEL_ACTION_DIM):
            raise ShapeMismatchError("pi0.5 Draft output must be [B,50,32]")
        if not bool(torch.isfinite(output).all().item()):
            raise ValueError("pi0.5 Draft output contains NaN or infinity")
        return output


def _reinitialize_action_head(head: Pi05DraftChunkHead, seed: int) -> None:
    device = head._action_head.weight.device  # noqa: SLF001
    cuda_devices: list[int] = []
    if device.type == "cuda":
        cuda_devices = [int(device.index if device.index is not None else 0)]
    with torch.random.fork_rng(devices=cuda_devices):
        torch.manual_seed(int(seed))
        if device.type == "cuda":
            torch.cuda.manual_seed_all(int(seed))
        nn.init.kaiming_uniform_(head._action_head.weight, a=math.sqrt(5))  # noqa: SLF001
        fan_in, _ = nn.init._calculate_fan_in_and_fan_out(  # noqa: SLF001
            head._action_head.weight  # noqa: SLF001
        )
        bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
        nn.init.uniform_(head._action_head.bias, -bound, bound)  # noqa: SLF001


def derive_pi05_draft_from_warm_start(
    warm_start: DraftChunkHead,
    *,
    target_contract: Pi05DraftTargetContract,
    initialization_seed: int,
    device: str | torch.device | None = None,
) -> tuple[Pi05DraftChunkHead, Pi05DraftTransferReport]:
    """Create an untrained 32D candidate from a strictly loaded 7D head."""

    if type(warm_start) is not DraftChunkHead:
        raise TypeError("warm_start must be an exact published DraftChunkHead")
    if (
        not warm_start.initialization_only
        or warm_start.production_compatible
        or warm_start.base_model_family != "pi0"
    ):
        raise ConfigurationError(
            "source Draft must be loaded with purpose='warm_start'"
        )
    checkpoint_path = warm_start.checkpoint_path
    if checkpoint_path is None or not checkpoint_path.is_file():
        raise ConfigurationError(
            "warm-start head is not bound to a strictly loaded checkpoint file"
        )
    checkpoint_sha256 = _sha256_file(checkpoint_path)
    if checkpoint_sha256 not in _PUBLISHED_PARENT_SHA256S:
        raise ConfigurationError(
            "warm-start checkpoint is not one of the four published SHA-256 assets"
        )
    if initialization_seed < 0:
        raise ConfigurationError("initialization_seed must be non-negative")

    source = warm_start.state_dict()
    if set(source) != set(_TARGET_STATE_SHAPES):
        raise ConfigurationError("warm-start state_dict keys changed after strict load")
    for name, target_shape in _TARGET_STATE_SHAPES.items():
        expected_shape = _SOURCE_ACTION_SHAPES.get(name, target_shape)
        if tuple(source[name].shape) != expected_shape:
            raise ConfigurationError(
                f"warm-start tensor {name!r} must have shape {expected_shape}"
            )

    lineage = WarmStartLineage(
        checkpoint_filename=checkpoint_path.name,
        checkpoint_size=checkpoint_path.stat().st_size,
        checkpoint_sha256=checkpoint_sha256,
        initialization_seed=int(initialization_seed),
    )
    target_device = device
    if target_device is None:
        target_device = next(warm_start.parameters()).device
    target = Pi05DraftChunkHead(
        target_contract=target_contract,
        warm_start_lineage=lineage,
        initialization_seed=int(initialization_seed),
        device=target_device,
    )
    target_state = target.state_dict()
    target_dtype = _torch_dtype(target_contract.draft_parameter_dtype)
    with torch.no_grad():
        for name in _COPIED_KEYS:
            if tuple(source[name].shape) != tuple(target_state[name].shape):
                raise ConfigurationError(f"warm-start shape mismatch for {name!r}")
            target_state[name].copy_(
                source[name].to(device=target_state[name].device, dtype=target_dtype)
            )
    _reinitialize_action_head(target, int(initialization_seed))
    target._source_checkpoint_path = checkpoint_path.resolve()  # noqa: SLF001

    parameter_count = sum(parameter.numel() for parameter in target.parameters())
    if parameter_count != PI05_DRAFT_PARAMETER_COUNT:
        raise ConfigurationError(
            "pi0.5 Draft parameter count mismatch: "
            f"expected {PI05_DRAFT_PARAMETER_COUNT}, got {parameter_count}"
        )
    copied_parameter_count = sum(source[name].numel() for name in _COPIED_KEYS)
    if copied_parameter_count != 110_274_560:
        raise ConfigurationError("warm-start copied parameter count changed")
    return target, Pi05DraftTransferReport(
        copied_keys=_COPIED_KEYS,
        reinitialized_keys=_REINITIALIZED_KEYS,
        copied_parameter_count=copied_parameter_count,
        target_parameter_count=parameter_count,
        warm_start_sha256=checkpoint_sha256,
    )


@dataclass(frozen=True, kw_only=True)
class Pi05DraftLossConfig:
    """Weights for model-space H=50/A=32 teacher distillation."""

    executed_prefix_steps: int = 12
    prefix_weight: float = 1.0
    tail_weight: float = 0.1
    padding_weight: float = 0.1
    huber_beta: float = 1.0

    def __post_init__(self) -> None:
        if not 1 <= self.executed_prefix_steps <= PI05_ACTION_HORIZON:
            raise ConfigurationError("executed_prefix_steps must be in [1, 50]")
        for name in ("prefix_weight", "tail_weight", "padding_weight", "huber_beta"):
            value = float(getattr(self, name))
            if not math.isfinite(value) or value <= 0:
                raise ConfigurationError(f"{name} must be finite and positive")


def build_pi05_draft_loss_mask(
    *,
    batch_size: int,
    device: str | torch.device,
    dtype: torch.dtype = torch.float32,
    config: Pi05DraftLossConfig | None = None,
    valid_steps: torch.Tensor | None = None,
) -> torch.Tensor:
    """Build a weighted ``[B,50,32]`` mask without hiding padded dimensions."""

    cfg = config or Pi05DraftLossConfig()
    if batch_size <= 0:
        raise ConfigurationError("batch_size must be positive")
    if not torch.is_floating_point(torch.empty((), dtype=dtype)):
        raise ConfigurationError("loss mask dtype must be floating")
    step_weights = torch.full(
        (PI05_ACTION_HORIZON,),
        float(cfg.tail_weight),
        device=device,
        dtype=dtype,
    )
    step_weights[: cfg.executed_prefix_steps] = float(cfg.prefix_weight)
    action_weights = torch.full(
        (PI05_MODEL_ACTION_DIM,),
        float(cfg.padding_weight),
        device=device,
        dtype=dtype,
    )
    action_weights[:PI05_ENV_ACTION_DIM] = 1.0
    mask = step_weights[None, :, None] * action_weights[None, None, :]
    mask = mask.expand(batch_size, -1, -1).clone()
    if valid_steps is not None:
        if not isinstance(valid_steps, torch.Tensor) or tuple(valid_steps.shape) != (
            batch_size,
            PI05_ACTION_HORIZON,
        ):
            raise ShapeMismatchError("valid_steps must be [B,50]")
        if valid_steps.dtype != torch.bool:
            raise ConfigurationError("valid_steps must use torch.bool")
        mask *= valid_steps.to(device=device)[:, :, None]
    if not bool((mask > 0).any().item()):
        raise ConfigurationError("loss mask selects no elements")
    return mask


def pi05_draft_distillation_loss(
    prediction: torch.Tensor,
    teacher_target: torch.Tensor,
    *,
    loss_mask: torch.Tensor | None = None,
    config: Pi05DraftLossConfig | None = None,
) -> torch.Tensor:
    """Weighted Smooth-L1 loss over the exact normalized model-space chunk."""

    if not isinstance(prediction, torch.Tensor) or prediction.ndim != 3:
        raise ShapeMismatchError("prediction must be [B,50,32]")
    expected = (int(prediction.shape[0]), PI05_ACTION_HORIZON, PI05_MODEL_ACTION_DIM)
    if tuple(prediction.shape) != expected:
        raise ShapeMismatchError(f"prediction must be [B,50,32]; expected {expected}")
    if (
        not isinstance(teacher_target, torch.Tensor)
        or tuple(teacher_target.shape) != expected
    ):
        raise ShapeMismatchError(f"teacher_target must have shape {expected}")
    if (
        prediction.device != teacher_target.device
        or prediction.dtype != teacher_target.dtype
    ):
        raise ConfigurationError(
            "prediction and teacher_target must use the same device and dtype"
        )
    if not torch.is_floating_point(prediction):
        raise ConfigurationError("distillation tensors must use a floating dtype")
    if not bool(torch.isfinite(prediction).all().item()) or not bool(
        torch.isfinite(teacher_target).all().item()
    ):
        raise ConfigurationError("distillation tensors contain NaN or infinity")
    cfg = config or Pi05DraftLossConfig()
    if loss_mask is None:
        loss_mask = build_pi05_draft_loss_mask(
            batch_size=expected[0],
            device=prediction.device,
            dtype=prediction.dtype,
            config=cfg,
        )
    if not isinstance(loss_mask, torch.Tensor) or tuple(loss_mask.shape) != expected:
        raise ShapeMismatchError(f"loss_mask must have shape {expected}")
    if loss_mask.device != prediction.device:
        raise ConfigurationError("loss_mask must be on the prediction device")
    weights = loss_mask.to(dtype=prediction.dtype)
    if not bool(torch.isfinite(weights).all().item()) or bool(
        (weights < 0).any().item()
    ):
        raise ConfigurationError("loss_mask must be finite and non-negative")
    denominator = weights.sum()
    if not bool((denominator > 0).item()):
        raise ConfigurationError("loss_mask selects no elements")
    elementwise = F.smooth_l1_loss(
        prediction,
        teacher_target,
        reduction="none",
        beta=float(cfg.huber_beta),
    )
    return (elementwise * weights).sum() / denominator


def _state_schema(
    state_dict: Mapping[str, torch.Tensor],
) -> dict[str, dict[str, Any]]:
    return {
        name: {
            "shape": list(tensor.shape),
            "dtype": _dtype_name(tensor.dtype),
        }
        for name, tensor in sorted(state_dict.items())
    }


def _validate_target_state_dict(
    state_dict: Mapping[str, torch.Tensor],
    target: Pi05DraftTargetContract,
    *,
    expected_schema: Mapping[str, Any] | None = None,
) -> None:
    if set(state_dict) != set(_TARGET_STATE_SHAPES):
        missing = sorted(set(_TARGET_STATE_SHAPES) - set(state_dict))
        unexpected = sorted(set(state_dict) - set(_TARGET_STATE_SHAPES))
        raise ConfigurationError(
            f"pi0.5 Draft state_dict keys mismatch: missing={missing}, "
            f"unexpected={unexpected}"
        )
    dtype = _torch_dtype(target.draft_parameter_dtype)
    for name, expected_shape in _TARGET_STATE_SHAPES.items():
        tensor = state_dict[name]
        if not isinstance(tensor, torch.Tensor):
            raise ConfigurationError(f"state_dict {name!r} is not a tensor")
        if tuple(tensor.shape) != expected_shape:
            raise ConfigurationError(
                f"state_dict {name!r} shape mismatch: "
                f"expected {expected_shape}, got {tuple(tensor.shape)}"
            )
        if tensor.dtype != dtype:
            raise ConfigurationError(
                f"state_dict {name!r} dtype mismatch: expected {dtype}, got {tensor.dtype}"
            )
    if (
        sum(tensor.numel() for tensor in state_dict.values())
        != PI05_DRAFT_PARAMETER_COUNT
    ):
        raise ConfigurationError("pi0.5 Draft state_dict parameter count mismatch")
    if expected_schema is not None and _state_schema(state_dict) != dict(
        expected_schema
    ):
        raise ConfigurationError("state_dict schema differs from signed manifest")


def _state_dict_content_sha256(state_dict: Mapping[str, torch.Tensor]) -> str:
    digest = hashlib.sha256()
    for name in sorted(state_dict):
        tensor = state_dict[name]
        if tensor.device.type == "meta":
            raise ConfigurationError("cannot export or hash meta-device Draft weights")
        header = _canonical_json_bytes(
            {
                "name": name,
                "shape": list(tensor.shape),
                "dtype": _dtype_name(tensor.dtype),
            }
        )
        digest.update(len(header).to_bytes(8, "big"))
        digest.update(header)
        raw = tensor.detach().to(device="cpu").contiguous().view(torch.uint8)
        digest.update(raw.numpy().tobytes(order="C"))
    return digest.hexdigest()


def _save_safetensors(
    path: Path,
    state_dict: Mapping[str, torch.Tensor],
    metadata: Mapping[str, str],
) -> None:
    try:
        from safetensors.torch import save_file
    except ImportError as error:
        raise OptionalDependencyError(
            "safetensors is required for Draft export"
        ) from error
    cpu_state = {
        name: tensor.detach().to(device="cpu").contiguous()
        for name, tensor in state_dict.items()
    }
    save_file(cpu_state, str(path), metadata=dict(metadata))


def _load_safetensors(path: Path, device: torch.device) -> dict[str, torch.Tensor]:
    try:
        from safetensors.torch import load_file
    except ImportError as error:
        raise OptionalDependencyError(
            "safetensors is required for Draft loading"
        ) from error
    return load_file(str(path), device=str(device))


def _read_safetensors_metadata(path: Path) -> dict[str, str]:
    try:
        from safetensors import safe_open
    except ImportError as error:
        raise OptionalDependencyError(
            "safetensors is required for Draft loading"
        ) from error
    with safe_open(str(path), framework="pt", device="cpu") as handle:
        return dict(handle.metadata() or {})


@dataclass(frozen=True)
class Pi05DraftCandidateArtifact:
    weights_path: Path
    manifest_path: Path
    weights_sha256: str
    state_dict_content_sha256: str
    manifest_sha256: str
    target_contract_sha256: str


def export_pi05_draft_candidate(
    head: Pi05DraftChunkHead,
    *,
    training_record: Pi05DraftTrainingRecord,
    output_dir: str | Path,
) -> Pi05DraftCandidateArtifact:
    """Export a trained but explicitly non-production candidate artifact."""

    if not isinstance(head, Pi05DraftChunkHead):
        raise TypeError("head must be a Pi05DraftChunkHead")
    if head.production_compatible:
        raise ConfigurationError(
            "production-loaded heads cannot be re-exported as candidates"
        )
    if head.training_step_count <= 0:
        raise ConfigurationError("untrained pi0.5 Draft cannot be exported")
    if head.training_step_count != training_record.optimizer_steps:
        raise ConfigurationError(
            "training record optimizer_steps does not match the head session"
        )
    source_path = head._source_checkpoint_path  # noqa: SLF001
    if source_path is None or not source_path.is_file():
        raise ConfigurationError("warm-start source path is unavailable at export")
    if _sha256_file(source_path) != head.warm_start_lineage.checkpoint_sha256:
        raise ConfigurationError("warm-start checkpoint changed after derivation")

    state_dict = head.state_dict()
    _validate_target_state_dict(state_dict, head.target_contract)
    state_content_sha256 = _state_dict_content_sha256(state_dict)
    schema = _state_schema(state_dict)
    schema_sha256 = _canonical_sha256(schema)

    root = Path(output_dir).expanduser().resolve()
    try:
        root.mkdir(parents=True, exist_ok=False)
    except FileExistsError as error:
        raise ConfigurationError(
            f"candidate output directory already exists: {root}"
        ) from error
    weights_path = root / "draft_model.safetensors"
    manifest_path = root / "artifact_manifest.json"
    _save_safetensors(
        weights_path,
        state_dict,
        {
            "artifact_kind": PI05_DRAFT_ARTIFACT_KIND,
            "production_authorized": "false",
            "target_contract_sha256": head.target_contract.sha256,
            "state_dict_content_sha256": state_content_sha256,
            "state_schema_sha256": schema_sha256,
        },
    )
    weights_sha256 = _sha256_file(weights_path)
    manifest = {
        "schema_version": 1,
        "artifact_kind": PI05_DRAFT_ARTIFACT_KIND,
        "production_authorized": False,
        "architecture": {
            "id": PI05_DRAFT_ARCHITECTURE,
            "action_horizon": PI05_ACTION_HORIZON,
            "model_action_dim": PI05_MODEL_ACTION_DIM,
            "environment_action_dim": PI05_ENV_ACTION_DIM,
            "model_state_dim": PI05_MODEL_STATE_DIM,
            "prefix_embedding_dim": PI05_PREFIX_EMBEDDING_DIM,
            "parameter_count": PI05_DRAFT_PARAMETER_COUNT,
            "active_joint_indices": list(_ACTIVE_JOINT_INDICES),
            "gripper_indices": list(_GRIPPER_INDICES),
        },
        "target_contract": head.target_contract.to_dict(),
        "target_contract_sha256": head.target_contract.sha256,
        "warm_start": head.warm_start_lineage.to_dict(),
        "training": training_record.to_dict(),
        "weights": {
            "path": weights_path.name,
            "size": weights_path.stat().st_size,
            "sha256": weights_sha256,
            "state_dict_content_sha256": state_content_sha256,
            "state_schema": schema,
            "state_schema_sha256": schema_sha256,
        },
    }
    manifest_path.write_bytes(_canonical_json_bytes(manifest) + b"\n")
    manifest_sha256 = _sha256_file(manifest_path)
    return Pi05DraftCandidateArtifact(
        weights_path=weights_path,
        manifest_path=manifest_path,
        weights_sha256=weights_sha256,
        state_dict_content_sha256=state_content_sha256,
        manifest_sha256=manifest_sha256,
        target_contract_sha256=head.target_contract.sha256,
    )


def _read_json_object(path: Path, name: str) -> Mapping[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ConfigurationError(f"failed to read {name} {path}: {error}") from error
    if not isinstance(value, Mapping):
        raise ConfigurationError(f"{name} must be a JSON object")
    return value


def _validate_evaluation_report(
    report: Mapping[str, Any],
    *,
    artifact_manifest_sha256: str,
    target_contract_sha256: str,
) -> None:
    expected = {
        "schema_version",
        "artifact_manifest_sha256",
        "target_contract_sha256",
        "protocol_id",
        "passed",
        "metrics",
    }
    _require_exact_keys(report, expected, name="evaluation_report")
    if report["schema_version"] != 1:
        raise ConfigurationError("unsupported evaluation report schema")
    if (
        _require_sha256(
            report["artifact_manifest_sha256"], "evaluation artifact manifest"
        )
        != artifact_manifest_sha256
    ):
        raise ConfigurationError("evaluation report targets another candidate")
    if (
        _require_sha256(report["target_contract_sha256"], "evaluation target contract")
        != target_contract_sha256
    ):
        raise ConfigurationError("evaluation report targets another policy contract")
    _require_string(report["protocol_id"], "evaluation protocol_id")
    if report["passed"] is not True:
        raise ConfigurationError("evaluation report did not pass")
    metrics = report["metrics"]
    if not isinstance(metrics, Mapping) or not metrics:
        raise ConfigurationError("evaluation metrics must be a non-empty object")
    for name, value in metrics.items():
        _require_string(name, "evaluation metric name")
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ConfigurationError(f"evaluation metric {name!r} must be numeric")
        if not math.isfinite(float(value)):
            raise ConfigurationError(f"evaluation metric {name!r} is not finite")


def _approval_unsigned_payload(
    *,
    artifact_manifest_sha256: str,
    weights_sha256: str,
    target_contract_sha256: str,
    evaluation_report_sha256: str,
    signing_key_id: str,
) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "decision": "approved_for_production",
        "signature_algorithm": "ed25519",
        "signing_key_id": _require_string(signing_key_id, "signing_key_id"),
        "artifact_manifest_sha256": _require_sha256(
            artifact_manifest_sha256, "artifact_manifest_sha256"
        ),
        "weights_sha256": _require_sha256(weights_sha256, "weights_sha256"),
        "target_contract_sha256": _require_sha256(
            target_contract_sha256, "target_contract_sha256"
        ),
        "evaluation_report_sha256": _require_sha256(
            evaluation_report_sha256, "evaluation_report_sha256"
        ),
    }


def sign_pi05_draft_candidate(
    *,
    candidate_manifest_path: str | Path,
    evaluation_report_path: str | Path,
    private_key_raw: bytes,
    signing_key_id: str,
    approval_path: str | Path,
) -> Path:
    """Sign an already evaluated candidate; never creates evaluation metrics."""

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    except ImportError as error:
        raise OptionalDependencyError(
            "cryptography is required for Draft signing"
        ) from error
    manifest_path = Path(candidate_manifest_path).expanduser().resolve()
    report_path = Path(evaluation_report_path).expanduser().resolve()
    manifest = _read_json_object(manifest_path, "candidate manifest")
    if manifest.get("production_authorized") is not False:
        raise ConfigurationError("only immutable candidate manifests may be signed")
    target_sha = _require_sha256(
        manifest.get("target_contract_sha256"), "manifest target_contract_sha256"
    )
    weights = manifest.get("weights")
    if not isinstance(weights, Mapping):
        raise ConfigurationError("candidate manifest weights must be an object")
    weights_sha = _require_sha256(weights.get("sha256"), "manifest weights.sha256")
    manifest_sha = _sha256_file(manifest_path)
    report = _read_json_object(report_path, "evaluation report")
    _validate_evaluation_report(
        report,
        artifact_manifest_sha256=manifest_sha,
        target_contract_sha256=target_sha,
    )
    payload = _approval_unsigned_payload(
        artifact_manifest_sha256=manifest_sha,
        weights_sha256=weights_sha,
        target_contract_sha256=target_sha,
        evaluation_report_sha256=_sha256_file(report_path),
        signing_key_id=signing_key_id,
    )
    if not isinstance(private_key_raw, bytes) or len(private_key_raw) != 32:
        raise ConfigurationError(
            "Ed25519 private_key_raw must contain exactly 32 bytes"
        )
    signature = Ed25519PrivateKey.from_private_bytes(private_key_raw).sign(
        _canonical_json_bytes(payload)
    )
    approval = dict(payload)
    approval["signature_base64"] = base64.b64encode(signature).decode("ascii")
    destination = Path(approval_path).expanduser().resolve()
    if destination.exists():
        raise ConfigurationError(f"approval path already exists: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(_canonical_json_bytes(approval) + b"\n")
    return destination


@dataclass(frozen=True)
class VerifiedPi05DraftPrediction:
    """A prediction bound to one signed artifact and exact target contract."""

    actions_model: torch.Tensor
    target_contract: Pi05DraftTargetContract
    artifact_manifest_sha256: str
    weights_sha256: str
    _owner_token: object = field(repr=False, compare=False)


class Pi05DraftProductionAdapter:
    """Inference-only facade created solely by the signed production loader."""

    def __init__(self, head: Pi05DraftChunkHead) -> None:
        if not head.production_compatible:
            raise ConfigurationError("pi0.5 Draft is not production-authorized")
        head.eval()
        head.requires_grad_(False)
        self._head = head
        self._owner_token = object()

    @property
    def head(self) -> Pi05DraftChunkHead:
        return self._head

    def predict(self, **inputs: torch.Tensor) -> VerifiedPi05DraftPrediction:
        if (
            not self._head.production_compatible
            or self._head.training
            or any(parameter.requires_grad for parameter in self._head.parameters())
        ):
            raise ConfigurationError(
                "production Draft must remain authorized, eval-only, and frozen"
            )
        with torch.inference_mode():
            actions = self._head(**inputs)
        expected = (
            int(inputs["robot_state"].shape[0]),
            PI05_ACTION_HORIZON,
            PI05_MODEL_ACTION_DIM,
        )
        if not isinstance(actions, torch.Tensor) or tuple(actions.shape) != expected:
            raise ShapeMismatchError(
                f"production Draft output must have shape {expected}"
            )
        if not bool(torch.isfinite(actions).all().item()):
            raise ValueError("production Draft output contains NaN or infinity")
        assert self._head._production_artifact_manifest_sha256 is not None  # noqa: SLF001
        assert self._head._production_weights_sha256 is not None  # noqa: SLF001
        return VerifiedPi05DraftPrediction(
            actions_model=actions,
            target_contract=self._head.target_contract,
            artifact_manifest_sha256=self._head._production_artifact_manifest_sha256,  # noqa: SLF001
            weights_sha256=self._head._production_weights_sha256,  # noqa: SLF001
            _owner_token=self._owner_token,
        )

    def predict_for_target(
        self,
        verified_target: Any,
        **inputs: torch.Tensor,
    ) -> Any:
        """Issue the verifier's production prediction only for the exact main load."""

        from .openpi_speculative import _issue_verified_draft_prediction

        self._head.target_contract.require_matches_verified_openpi(verified_target)
        prediction = self.predict(**inputs)
        main_contract = verified_target.contract
        return _issue_verified_draft_prediction(
            actions_model=prediction.actions_model,
            target=verified_target,
            target_contract=main_contract,
            draft_checkpoint_id=(
                "fibocom-pi05-draft@manifest-sha256:"
                f"{prediction.artifact_manifest_sha256}"
            ),
            draft_checkpoint_sha256=prediction.weights_sha256,
        )

    __call__ = predict


def _verify_approval(
    approval: Mapping[str, Any],
    *,
    trusted_public_key_raw: bytes,
    trusted_signing_key_id: str,
) -> Mapping[str, Any]:
    try:
        from cryptography.exceptions import InvalidSignature
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
    except ImportError as error:
        raise OptionalDependencyError(
            "cryptography is required for Draft signature verification"
        ) from error
    expected = {
        "schema_version",
        "decision",
        "signature_algorithm",
        "signing_key_id",
        "artifact_manifest_sha256",
        "weights_sha256",
        "target_contract_sha256",
        "evaluation_report_sha256",
        "signature_base64",
    }
    _require_exact_keys(approval, expected, name="production_approval")
    payload = _approval_unsigned_payload(
        artifact_manifest_sha256=approval["artifact_manifest_sha256"],
        weights_sha256=approval["weights_sha256"],
        target_contract_sha256=approval["target_contract_sha256"],
        evaluation_report_sha256=approval["evaluation_report_sha256"],
        signing_key_id=approval["signing_key_id"],
    )
    if approval["schema_version"] != 1:
        raise ConfigurationError("unsupported production approval schema")
    if approval["decision"] != "approved_for_production":
        raise ConfigurationError("production approval decision is not approved")
    if approval["signature_algorithm"] != "ed25519":
        raise ConfigurationError("production approval must use Ed25519")
    if approval["signing_key_id"] != trusted_signing_key_id:
        raise ConfigurationError("production approval signing key is not trusted")
    if (
        not isinstance(trusted_public_key_raw, bytes)
        or len(trusted_public_key_raw) != 32
    ):
        raise ConfigurationError("trusted Ed25519 public key must contain 32 bytes")
    try:
        signature = base64.b64decode(approval["signature_base64"], validate=True)
    except (TypeError, ValueError) as error:
        raise ConfigurationError(
            "production approval signature is not valid base64"
        ) from error
    try:
        Ed25519PublicKey.from_public_bytes(trusted_public_key_raw).verify(
            signature, _canonical_json_bytes(payload)
        )
    except InvalidSignature as error:
        raise ConfigurationError(
            "production approval signature verification failed"
        ) from error
    return payload


def load_production_pi05_draft(
    *,
    candidate_manifest_path: str | Path,
    approval_path: str | Path,
    evaluation_report_path: str | Path,
    expected_target: Pi05DraftTargetContract,
    trusted_public_key_raw: bytes,
    trusted_signing_key_id: str,
    device: str | torch.device,
) -> Pi05DraftProductionAdapter:
    """Load only a hash-complete, evaluated, Ed25519-approved Draft."""

    manifest_path = Path(candidate_manifest_path).expanduser().resolve()
    approval_file = Path(approval_path).expanduser().resolve()
    report_path = Path(evaluation_report_path).expanduser().resolve()
    manifest = _read_json_object(manifest_path, "candidate manifest")
    approval = _read_json_object(approval_file, "production approval")
    approval_payload = _verify_approval(
        approval,
        trusted_public_key_raw=trusted_public_key_raw,
        trusted_signing_key_id=trusted_signing_key_id,
    )
    manifest_sha = _sha256_file(manifest_path)
    if approval_payload["artifact_manifest_sha256"] != manifest_sha:
        raise ConfigurationError("signed approval targets another candidate manifest")

    expected_top = {
        "schema_version",
        "artifact_kind",
        "production_authorized",
        "architecture",
        "target_contract",
        "target_contract_sha256",
        "warm_start",
        "training",
        "weights",
    }
    _require_exact_keys(manifest, expected_top, name="candidate manifest")
    if manifest["schema_version"] != 1:
        raise ConfigurationError("unsupported candidate manifest schema")
    if manifest["artifact_kind"] != PI05_DRAFT_ARTIFACT_KIND:
        raise ConfigurationError("candidate artifact kind mismatch")
    if manifest["production_authorized"] is not False:
        raise ConfigurationError("candidate manifest must remain non-production")

    target = Pi05DraftTargetContract.from_dict(manifest["target_contract"])
    if target != expected_target:
        raise ConfigurationError(
            "candidate target contract differs from loaded main policy"
        )
    if manifest["target_contract_sha256"] != target.sha256:
        raise ConfigurationError("candidate target-contract SHA-256 mismatch")
    if approval_payload["target_contract_sha256"] != target.sha256:
        raise ConfigurationError("signed approval targets another target contract")

    architecture = manifest["architecture"]
    expected_architecture = {
        "id": PI05_DRAFT_ARCHITECTURE,
        "action_horizon": PI05_ACTION_HORIZON,
        "model_action_dim": PI05_MODEL_ACTION_DIM,
        "environment_action_dim": PI05_ENV_ACTION_DIM,
        "model_state_dim": PI05_MODEL_STATE_DIM,
        "prefix_embedding_dim": PI05_PREFIX_EMBEDDING_DIM,
        "parameter_count": PI05_DRAFT_PARAMETER_COUNT,
        "active_joint_indices": list(_ACTIVE_JOINT_INDICES),
        "gripper_indices": list(_GRIPPER_INDICES),
    }
    if architecture != expected_architecture:
        raise ConfigurationError("candidate architecture contract mismatch")
    lineage = WarmStartLineage.from_dict(manifest["warm_start"])
    training = manifest["training"]
    if not isinstance(training, Mapping):
        raise ConfigurationError("candidate training record must be an object")
    Pi05DraftTrainingRecord(**dict(training))

    report = _read_json_object(report_path, "evaluation report")
    _validate_evaluation_report(
        report,
        artifact_manifest_sha256=manifest_sha,
        target_contract_sha256=target.sha256,
    )
    if approval_payload["evaluation_report_sha256"] != _sha256_file(report_path):
        raise ConfigurationError("signed evaluation report SHA-256 mismatch")

    weights = manifest["weights"]
    if not isinstance(weights, Mapping):
        raise ConfigurationError("candidate weights must be an object")
    expected_weight_keys = {
        "path",
        "size",
        "sha256",
        "state_dict_content_sha256",
        "state_schema",
        "state_schema_sha256",
    }
    _require_exact_keys(weights, expected_weight_keys, name="candidate weights")
    filename = _require_string(weights["path"], "weights.path")
    if Path(filename).name != filename or not filename.endswith(".safetensors"):
        raise ConfigurationError("weights.path must be one safetensors filename")
    weights_path = (manifest_path.parent / filename).resolve()
    if weights_path.parent != manifest_path.parent or not weights_path.is_file():
        raise ConfigurationError(
            "candidate weights are missing or escape artifact root"
        )
    if isinstance(weights["size"], bool) or not isinstance(weights["size"], int):
        raise ConfigurationError("weights.size must be an integer")
    if weights_path.stat().st_size != weights["size"]:
        raise ConfigurationError("candidate weights size mismatch")
    weights_sha = _sha256_file(weights_path)
    if weights_sha != _require_sha256(weights["sha256"], "weights.sha256"):
        raise ConfigurationError("candidate weights SHA-256 mismatch")
    if approval_payload["weights_sha256"] != weights_sha:
        raise ConfigurationError("signed approval targets another weights file")
    if _canonical_sha256(weights["state_schema"]) != _require_sha256(
        weights["state_schema_sha256"], "weights.state_schema_sha256"
    ):
        raise ConfigurationError("candidate state schema SHA-256 mismatch")

    metadata = _read_safetensors_metadata(weights_path)
    expected_metadata = {
        "artifact_kind": PI05_DRAFT_ARTIFACT_KIND,
        "production_authorized": "false",
        "target_contract_sha256": target.sha256,
        "state_dict_content_sha256": weights["state_dict_content_sha256"],
        "state_schema_sha256": weights["state_schema_sha256"],
    }
    if metadata != expected_metadata:
        raise ConfigurationError("safetensors metadata differs from signed manifest")

    target_device = torch.device(device)
    state_dict = _load_safetensors(weights_path, target_device)
    _validate_target_state_dict(
        state_dict, target, expected_schema=weights["state_schema"]
    )
    content_sha = _state_dict_content_sha256(state_dict)
    if content_sha != _require_sha256(
        weights["state_dict_content_sha256"], "weights.state_dict_content_sha256"
    ):
        raise ConfigurationError("candidate state_dict content SHA-256 mismatch")

    head = Pi05DraftChunkHead(
        target_contract=target,
        warm_start_lineage=lineage,
        initialization_seed=lineage.initialization_seed,
        device=target_device,
    )
    incompatible = head.load_state_dict(state_dict, strict=True)
    if incompatible.missing_keys or incompatible.unexpected_keys:
        raise ConfigurationError(
            "strict pi0.5 Draft load returned incompatible state_dict keys"
        )
    head._authorize_production(  # noqa: SLF001
        _PRODUCTION_AUTHORIZATION_TOKEN,
        artifact_manifest_sha256=manifest_sha,
        weights_sha256=weights_sha,
    )
    return head.production_predict_adapter()


__all__ = [
    "PI05_ACTION_HORIZON",
    "PI05_DRAFT_ARCHITECTURE",
    "PI05_DRAFT_ARTIFACT_KIND",
    "PI05_DRAFT_PARAMETER_COUNT",
    "PI05_ENV_ACTION_DIM",
    "PI05_MAX_TOKEN_LENGTH",
    "PI05_MODEL_ACTION_DIM",
    "PI05_MODEL_STATE_DIM",
    "PI05_PREFIX_EMBEDDING_DIM",
    "PI05_PARENT_REPOSITORY_ID",
    "PI05_PARENT_REVISION",
    "PI05_RAW_STATE_DIM",
    "Pi05DraftCandidateArtifact",
    "Pi05DraftChunkHead",
    "Pi05DraftLossConfig",
    "Pi05DraftProductionAdapter",
    "Pi05DraftTargetContract",
    "Pi05DraftTrainingRecord",
    "Pi05DraftTransferReport",
    "VerifiedPi05DraftPrediction",
    "WarmStartLineage",
    "build_pi05_draft_loss_mask",
    "derive_pi05_draft_from_warm_start",
    "export_pi05_draft_candidate",
    "load_production_pi05_draft",
    "pi05_draft_distillation_loss",
    "sign_pi05_draft_candidate",
]
